[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
remappings = ['@openzeppelin/=node_modules/@openzeppelin/']

[rpc_endpoints]
monad = "https://testnet-rpc.monad.xyz/"

[etherscan]
monad = { key = "your-etherscan-api-key", url = "https://testnet.monadexplorer.com/api" }
